<svelte:head>
	<title>FormValidation • Integrating with TinyMCE</title>
</svelte:head>

<GuideLayout>
    <h1 class="tc lh-copy">Integrating with TinyMCE</h1>
    
    <section class="mv5">
        <p class="lh-copy">Most of <a href="http://en.wikipedia.org/wiki/WYSIWYG" class="blue dim link">WYSIWYG</a> (What You See Is What You Get) editors generate some HTML tags for an empty string. So, basically, you can't use notEmpty validator to validate a text area which uses a WYSIWYG editor.</p>
        <p class="lh-copy">Instead, use the <a href="/guide/validators/callback" class="blue dim link">callback</a> validator to get the raw HTML string, and check if it's the default value generated by the editor, then it's empty field.</p>
        <p class="lh-copy">The following example demonstrates how to do it with the <a href="https://www.tinymce.com" class="blue dim link">TinyMCE</a> editor.</p>
        <Demo prefix="/guide/examples/integrating-with-tinymce" frameworks={['tachyons']} />
    </section>

    <Examples examples={[
        'Integrating with Summernote',
        'Integrating with TinyMCE',
    ]} />

    <RelatedValidators validators={['callback', 'notEmpty', 'stringLength']} />
</GuideLayout>

<script>
import Demo from '../../../../components/Demo.svelte';
import Examples from '../../../../components/Examples.svelte';
import GuideLayout from '../../../../components/GuideLayout.svelte';
import RelatedValidators from '../../../../components/RelatedValidators.svelte';
</script>
