<svelte:head>
	<title>FormValidation • Recaptcha3Token plugin</title>
</svelte:head>

<GuideLayout>
    <h1 class="f3 f2-m f1-l tc">Recaptcha3Token plugin</h1>
    <h2 class="f4 fw4 tc">Send the Google reCAPTCHA v3 token to the back-end when the form is valid</h2>

    <Tip>Use the <a href="/guide/plugins/recaptcha3" class="blue dim link">Recaptcha3</a> plugin if you want to verify the Google reCAPTCHA v3 token</Tip>

    <section class="mv5">
        <Heading>Usage</Heading>
        <p class="lh-copy">To use it, you need to register a site and secret keys at <a href="https://www.google.com/recaptcha/admin" class="blue dim link">https://www.google.com/recaptcha/admin</a>.</p>
        <p class="lh-copy">The following piece of code is the starting point to use the Recaptcha3Token plugin:</p>
<SampleCode lang="html" code={`
<html>
<head>
    <link-tag rel="stylesheet" href="/vendors/formvalidation/dist/css/formValidation.min.css">
</head>
<body>
    <form id="demoForm" method="POST">
        ...
    </form>

<script-tag src="https://cdnjs.cloudflare.com/ajax/libs/es6-shim/0.35.3/es6-shim.min.js"></script-tag>    
<script-tag src="/vendors/formvalidation/dist/js/FormValidation.min.js"></script-tag>
<script-tag src="/vendors/formvalidation/dist/js/plugins/Recaptcha3Token.min.js"></script-tag>

<script-tag>
document.addEventListener('DOMContentLoaded', function(e) {
    FormValidation.formValidation(
        document.getElementById('demoForm'),
        {
            fields: {
                ...
            },
            plugins: {
                ...,
                recaptcha3Token: new FormValidation.plugins.Recaptcha3Token({
                    action: ...,
                    hiddenTokenName: ...,
                    language: ...,
                    siteKey: ...,
                }),
            },
        }
    );
});
</script-tag>
</body>
</html>
`} />
        <p class="lh-copy">The sample code above assumes that the FormValidation files are placed inside the <code>vendors</code> directory. You might need to change the path depending on where you place them on the server.</p>
    </section>

    <section class="mv5">
        <Heading>Options</Heading>
        <p class="lh-copy i"><sup>*</sup> presents a required parameter</p>
        <table class="collapse ba br2 b--black-10 pv2 ph3 w-100">
            <tr class="striped--light-gray">
                <th class="pv2 ph3 tl f6 fw6 ttu">Option</th>
                <th class="pv2 ph3 tl f6 fw6 ttu">Type</th>
                <th class="pv2 ph3 tl f6 fw6 ttu">Description</th>
            </tr>
            <tr class="striped--light-gray">
                <td class="pv2 ph3"><code>action</code> <sup>*</sup></td>
                <td class="pv2 ph3">String</td>
                <td class="pv2 ph3">The page action</td>
            </tr>
            <tr class="striped--light-gray">
                <td class="pv2 ph3"><code>hiddenTokenName</code> <sup>*</sup></td>
                <td class="pv2 ph3">String</td>
                <td class="pv2 ph3 lh-copy">The name of hidden token input generated by Google reCAPTCHA v3</td>
            </tr>
            <tr class="striped--light-gray">
                <td class="pv2 ph3"><code>language</code></td>
                <td class="pv2 ph3">String</td>
                <td class="pv2 ph3 lh-copy">The <a href="https://developers.google.com/recaptcha/docs/language" class="blue dim link">language code</a> defined by reCAPTCHA</td>
            </tr>
            <tr class="striped--light-gray">
                <td class="pv2 ph3"><code>siteKey</code> <sup>*</sup></td>
                <td class="pv2 ph3">String</td>
                <td class="pv2 ph3">The site key provided by Google</td>
            </tr>
        </table>
    </section>
    
    <section class="mv5">
        <Heading>Changelog</Heading>
        <ul class="pa0 ma0 ml3 lh-copy">
            <li>v1.7.0: First release. It means that the Recaptcha3Token plugin requires FormValidation v1.7.0 or newer.</li>
        </ul>
    </section>

    <section class="mv5">
        <div class="flex">
            <PrevButton target="/guide/plugins/recaptcha3">Recaptcha3 plugin</PrevButton>
            <NextButton target="/guide/plugins/semantic">Semantic plugin</NextButton>
        </div>
    </section>
</GuideLayout>

<script>
import Heading from '../../../../components/Heading.svelte';
import GuideLayout from '../../../../components/GuideLayout.svelte';
import NextButton from '../../../../components/NextButton.svelte';
import PrevButton from '../../../../components/PrevButton.svelte';
import SampleCode from '../../../../components/SampleCode.svelte';
import Tip from '../../../../components/Tip.svelte';
</script>
