<svelte:head>
	<title>FormValidation • v0.4.5</title>
</svelte:head>

<ChangelogLayout>
    <h1 class="f3 f2-m f1-l tc">Version 0.4.5</h1>
    <h2 class="f4 fw4 tc">Released 15 May 2014</h2>

    <section class="mv5">
        <Heading>New features</Heading>
        <ul class="pa0 ma0 ml3 lh-copy">
            <li>Add <code>$.fn.bootstrapValidator.helpers.date</code> for validating a date, re-used in <a href="/guide/validators/date" class="blue dim link">date</a>, <a href="/guide/validators/id" class="blue dim link">id</a>, <a href="/guide/validators/vat" class="blue dim link">vat</a> validators</li>
            <li><i class="fa fa-star"></i> Add <a href="/guide/validators/id" class="blue dim link">id validator</a>, support 25 countries</li>
            <li><i class="fa fa-star"></i> Add <code>threshold</code> option</li>
            <li>Add <code>separator</code> option to the <a href="/guide/validators/numeric" class="blue dim link">numeric validator</a></li>
            <li>Add <a href="/guide/validators/isin" class="blue dim link">isin (International Securities Identification Number) validator</a></li>
            <li>Add <a href="/guide/validators/rtn" class="blue dim link">rtn (Routing transit number) validator</a></li>
            <li>Add <a href="/guide/validators/cusip" class="blue dim link">cusip (North American Securities) validator</a></li>
            <li>Add <a href="/guide/validators/sedol" class="blue dim link">sedol (Stock Exchange Daily Official List) validator</a></li>
        </ul>
    </section>

    <section class="mv5">
        <Heading>Improvements</Heading>
        <ul class="pa0 ma0 ml3 lh-copy">
            <li>The <a href="/guide/validators/zip-code" class="blue dim link">zipCode validator</a> adds support for Italian, Dutch postcodes</li>
            <li>Change default <code>submitButtons</code> to <code>[type="submit"]</code> to support <code>input type="submit"</code></li>
            <li>The cvv validator should support spaces in credit card</li>
        </ul>
    </section>

    <section class="mv5">
        <Heading>Bug fixes</Heading>
        <ul class="pa0 ma0 ml3 lh-copy">
            <li>Fix the issue that the hidden fields generated by other plugins might not be validated</li>
            <li>When parsing options from HTML attributes, don't add the field which hasn't validators</li>
            <li>Fix the conflict issue with MooTools</li>
            <li>The submit buttons are not sent</li>
            <li>The <a href="/guide/validators/iban" class="blue dim link">iban validator</a> does not work on IE8</li>
            <li>Plugin method invocation don't work</li>
        </ul>
    </section>
</ChangelogLayout>

<script>
import ChangelogLayout from '../../../components/ChangelogLayout.svelte';
import Heading from '../../../components/Heading.svelte';
</script>